version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: lending_app_db
      POSTGRES_USER: lending_app_user
      POSTGRES_PASSWORD: lending_app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: